### PR TITLE
Enable comment toggling functionality

### PR DESCRIPTION
**Pull request by parnham**
Created an `Earthly.tmPreferences` file which enables the `Toggle Comment` menu functionality and keyboard shortcut in sublimetext.

### CODE REVIEW

**Comment by adamgordonbell** [comment]
Thanks for the contribution @parnham!  @vladaionescu are you a sublime user?

**Comment by vladaionescu** [comment]
It's been a while since I was a user - wonder if @zedtux has some spare cycles to help us out with testing this feature. If not, I might give it a shot.

**Comment by zedtux** [comment]
I'm a Sublime user yes. I would be glad to help! I will give it a try and let you know 😉

**Comment by zedtux** [comment]
This works great.

Aside note: The XML is not very clean, there is `<dict>` tag which is not on a new line, and therefore all the other lines are not well indented.

Here is a "fixed" version:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Comments</string>
    <key>scope</key>
    <string>source.earthfile</string>
    <key>settings</key>
    <dict>
      <key>shellVariables</key>
      <array>
        <dict>
          <key>name</key>
          <string>TM_COMMENT_START</string>
          <key>value</key>
          <string># </string>
        </dict>
      </array>
    </dict>
  </dict>
</plist>
```

**Comment by parnham** [comment]
@zedtux Hopefully this fixes it?

**Comment by zedtux** [comment]
Yep it does! Nice work!

**Comment by zedtux** [comment]
You could go with a `git rebase -i master` and `fixup` the 3 last commit within the first one, just to clean the history ... or @vladaionescu could use the Github Squash feature.

**Comment by vladaionescu** [comment]
Awesome, thanks @parnham & @zedtux !

**Review by vladaionescu — APPROVED** [review]

**Pull request merged**
